paths:
  data_dir: "../data_generation/data/target"
  cond_dir: "../data_generation/data/condition"
  checkpoint_dir: "checkpoints"
  samples_dir: "samples"

image:
  size: 128
  channels: 3

training:
  batch_size: 32
  epochs: 300
  learning_rate: 0.0001
  weight_decay: 0.0001

diffusion:
  min_signal_rate: 0.02
  max_signal_rate: 0.95
  ema: 0.999
  diffusion_steps: 100

unet:
  noise_embedding_size: 32

logging:
  wandb: true
